export const learningService = {
  getLearningCategories() {
    return [
      {
        id: 'abc',
        name: 'ABC',
        icon: '🔤',
        color: '#FF6B9D',
        description: 'Learn English Alphabet',
      },
      {
        id: '123',
        name: '123',
        icon: '🔢',
        color: '#4ECDC4',
        description: 'Learn Numbers',
      },
      {
        id: 'urdu',
        name: 'Urdu Alif Bay Pay',
        icon: '📖',
        color: '#FFE66D',
        description: 'اردو الف بے پے',
      },
      {
        id: 'shapes',
        name: 'Shapes',
        icon: '🔷',
        color: '#A8E6CF',
        description: 'Learn Shapes',
      },
      {
        id: 'colors',
        name: 'Colors',
        icon: '🎨',
        color: '#FF8B94',
        description: 'Learn Colors',
      },
      {
        id: 'animals',
        name: 'Animals',
        icon: '🦁',
        color: '#C7CEEA',
        description: 'Learn Animals',
      },
      {
        id: 'fruits',
        name: 'Fruits & Vegetables',
        icon: '🍎',
        color: '#FFD93D',
        description: 'Learn Fruits & Vegetables',
      },
      {
        id: 'phonics',
        name: 'Phonics',
        icon: '🔊',
        color: '#95E1D3',
        description: 'Learn Phonics',
      },
    ];
  },

  getLearningContent(categoryId) {
    const content = {
      abc: [
        { id: 'a', letter: 'A', word: 'Apple', image: '🍎', audio: null },
        { id: 'b', letter: 'B', word: 'Ball', image: '⚽', audio: null },
        { id: 'c', letter: 'C', word: 'Cat', image: '🐱', audio: null },
        { id: 'd', letter: 'D', word: 'Dog', image: '🐶', audio: null },
        { id: 'e', letter: 'E', word: 'Elephant', image: '🐘', audio: null },
        { id: 'f', letter: 'F', word: 'Fish', image: '🐟', audio: null },
        { id: 'g', letter: 'G', word: 'Giraffe', image: '🦒', audio: null },
        { id: 'h', letter: 'H', word: 'House', image: '🏠', audio: null },
        { id: 'i', letter: 'I', word: 'Ice Cream', image: '🍦', audio: null },
        { id: 'j', letter: 'J', word: 'Jellyfish', image: '🎐', audio: null },
        { id: 'k', letter: 'K', word: 'Kite', image: '🪁', audio: null },
        { id: 'l', letter: 'L', word: 'Lion', image: '🦁', audio: null },
        { id: 'm', letter: 'M', word: 'Monkey', image: '🐵', audio: null },
        { id: 'n', letter: 'N', word: 'Nest', image: '🪺', audio: null },
        { id: 'o', letter: 'O', word: 'Octopus', image: '🐙', audio: null },
        { id: 'p', letter: 'P', word: 'Penguin', image: '🐧', audio: null },
        { id: 'q', letter: 'Q', word: 'Queen', image: '👑', audio: null },
        { id: 'r', letter: 'R', word: 'Rabbit', image: '🐰', audio: null },
        { id: 's', letter: 'S', word: 'Sun', image: '☀️', audio: null },
        { id: 't', letter: 'T', word: 'Tree', image: '🌳', audio: null },
        { id: 'u', letter: 'U', word: 'Umbrella', image: '☂️', audio: null },
        { id: 'v', letter: 'V', word: 'Violin', image: '🎻', audio: null },
        { id: 'w', letter: 'W', word: 'Watermelon', image: '🍉', audio: null },
        { id: 'x', letter: 'X', word: 'Xylophone', image: '🎹', audio: null },
        { id: 'y', letter: 'Y', word: 'Yacht', image: '⛵', audio: null },
        { id: 'z', letter: 'Z', word: 'Zebra', image: '🦓', audio: null },
      ],
      '123': [
        { id: '1', number: '1', word: 'One', image: '🍎', count: 1 },
        { id: '2', number: '2', word: 'Two', image: '🍎', count: 2 },
        { id: '3', number: '3', word: 'Three', image: '🍎', count: 3 },
        { id: '4', number: '4', word: 'Four', image: '🍎', count: 4 },
        { id: '5', number: '5', word: 'Five', image: '🍎', count: 5 },
        { id: '6', number: '6', word: 'Six', image: '⭐', count: 6 },
        { id: '7', number: '7', word: 'Seven', image: '⭐', count: 7 },
        { id: '8', number: '8', word: 'Eight', image: '⭐', count: 8 },
        { id: '9', number: '9', word: 'Nine', image: '⭐', count: 9 },
        { id: '10', number: '10', word: 'Ten', image: '⭐', count: 10 },
      ],
      urdu: [
        { id: 'alif', letter: 'ا', name: 'Alif', word: 'آدمی', image: '👤' },
        { id: 'bay', letter: 'ب', name: 'Bay', word: 'بلی', image: '🐱' },
        { id: 'pay', letter: 'پ', name: 'Pay', word: 'پانی', image: '💧' },
        { id: 'tay', letter: 'ت', name: 'Tay', word: 'ٹماٹر', image: '🍅' },
        { id: 'tthay', letter: 'ٹ', name: 'Tthay', word: 'ٹماٹر', image: '🍅' },
        { id: 'say', letter: 'ث', name: 'Say', word: 'سیب', image: '🍎' },
        { id: 'jeem', letter: 'ج', name: 'Jeem', word: 'جگ', image: '🏺' },
        { id: 'chay', letter: 'چ', name: 'Chay', word: 'چاند', image: '🌙' },
        { id: 'hay', letter: 'ح', name: 'Hay', word: 'ہاتھی', image: '🐘' },
        { id: 'khay', letter: 'خ', name: 'Khay', word: 'خربوزہ', image: '🍈' },
        { id: 'daal', letter: 'د', name: 'Daal', word: 'دودھ', image: '🥛' },
        { id: 'dhaal', letter: 'ڈ', name: 'Dhaal', word: 'ڈول', image: '🪣' },
        { id: 'zaal', letter: 'ذ', name: 'Zaal', word: 'ذہن', image: '🧠' },
        { id: 'ray', letter: 'ر', name: 'Ray', word: 'راستہ', image: '🛣️' },
        { id: 'rray', letter: 'ڑ', name: 'Rray', word: 'ڑکشہ', image: '🛺' },
        { id: 'zay', letter: 'ز', name: 'Zay', word: 'زمین', image: '🌍' },
        { id: 'zhay', letter: 'ژ', name: 'Zhay', word: 'ژالہ', image: '❄️' },
        { id: 'seen', letter: 'س', name: 'Seen', word: 'سورج', image: '☀️' },
        { id: 'sheen', letter: 'ش', name: 'Sheen', word: 'شیر', image: '🦁' },
        { id: 'swad', letter: 'ص', name: 'Swad', word: 'صبح', image: '🌅' },
        { id: 'zwad', letter: 'ض', name: 'Zwad', word: 'ضلع', image: '🗺️' },
        { id: 'toay', letter: 'ط', name: 'Toay', word: 'طوطا', image: '🦜' },
        { id: 'zoay', letter: 'ظ', name: 'Zoay', word: 'ظالم', image: '😠' },
        { id: 'ain', letter: 'ع', name: 'Ain', word: 'عینک', image: '👓' },
        { id: 'ghain', letter: 'غ', name: 'Ghain', word: 'غبارہ', image: '🎈' },
        { id: 'fay', letter: 'ف', name: 'Fay', word: 'فانوس', image: '🏮' },
        { id: 'qaaf', letter: 'ق', name: 'Qaaf', word: 'قلم', image: '✏️' },
        { id: 'kaaf', letter: 'ک', name: 'Kaaf', word: 'کتاب', image: '📚' },
        { id: 'gaaf', letter: 'گ', name: 'Gaaf', word: 'گلاب', image: '🌹' },
        { id: 'laam', letter: 'ل', name: 'Laam', word: 'لال', image: '🔴' },
        { id: 'meem', letter: 'م', name: 'Meem', word: 'مچھلی', image: '🐟' },
        { id: 'noon', letter: 'ن', name: 'Noon', word: 'نارنجی', image: '🍊' },
        { id: 'waao', letter: 'و', name: 'Waao', word: 'واٹر', image: '💧' },
        { id: 'hay2', letter: 'ہ', name: 'Hay', word: 'ہوا', image: '💨' },
        { id: 'hamza', letter: 'ء', name: 'Hamza', word: 'آب', image: '💦' },
        { id: 'chotiye', letter: 'ی', name: 'Choti Ye', word: 'یخ', image: '🧊' },
        { id: 'bariye', letter: 'ے', name: 'Bari Ye', word: 'ے', image: '✍️' },
      ],
      shapes: [
        { id: 'circle', name: 'Circle', shape: '⭕', color: 'red' },
        { id: 'square', name: 'Square', shape: '⬜', color: 'blue' },
        { id: 'triangle', name: 'Triangle', shape: '🔺', color: 'yellow' },
        { id: 'rectangle', name: 'Rectangle', shape: '▭', color: 'green' },
        { id: 'star', name: 'Star', shape: '⭐', color: 'gold' },
        { id: 'heart', name: 'Heart', shape: '❤️', color: 'pink' },
        { id: 'diamond', name: 'Diamond', shape: '💎', color: 'blue' },
        { id: 'oval', name: 'Oval', shape: '⚪', color: 'purple' },
        { id: 'pentagon', name: 'Pentagon', shape: '⬟', color: 'orange' },
        { id: 'hexagon', name: 'Hexagon', shape: '⬡', color: 'teal' },
        { id: 'octagon', name: 'Octagon', shape: '⯄', color: 'navy' },
        { id: 'crescent', name: 'Crescent', shape: '🌙', color: 'silver' },
        { id: 'arrow', name: 'Arrow', shape: '➡️', color: 'red' },
        { id: 'cross', name: 'Cross', shape: '➕', color: 'black' },
        { id: 'moon', name: 'Moon', shape: '🌙', color: 'yellow' },
      ],
      colors: [
        { id: 'red', name: 'Red', color: '#FF0000', examples: ['🍎', '🌹', '🚗'] },
        { id: 'blue', name: 'Blue', color: '#0000FF', examples: ['🦋', '🌊', '🔵'] },
        { id: 'green', name: 'Green', color: '#00FF00', examples: ['🌿', '🐸', '🥦'] },
        { id: 'yellow', name: 'Yellow', color: '#FFFF00', examples: ['🌻', '🍌', '⭐'] },
        { id: 'orange', name: 'Orange', color: '#FFA500', examples: ['🍊', '🥕', '🔥'] },
        { id: 'purple', name: 'Purple', color: '#800080', examples: ['🍇', '🔮', '💜'] },
        { id: 'pink', name: 'Pink', color: '#FFC0CB', examples: ['🌸', '🎀', '🐷'] },
        { id: 'brown', name: 'Brown', color: '#A52A2A', examples: ['🍫', '🐻', '🌰'] },
        { id: 'black', name: 'Black', color: '#000000', examples: ['🖤', '🐈‍⬛', '⚫'] },
        { id: 'white', name: 'White', color: '#FFFFFF', examples: ['🤍', '☁️', '⚪'] },
        { id: 'gray', name: 'Gray', color: '#808080', examples: ['🐘', '🌫️', '🔘'] },
        { id: 'navy', name: 'Navy Blue', color: '#000080', examples: ['🌌', '🔵', '💙'] },
        { id: 'maroon', name: 'Maroon', color: '#800000', examples: ['🍷', '❤️', '🔴'] },
        { id: 'teal', name: 'Teal', color: '#008080', examples: ['🦆', '💎', '🌊'] },
        { id: 'cyan', name: 'Cyan', color: '#00FFFF', examples: ['💧', '🌐', '🔷'] },
        { id: 'lime', name: 'Lime', color: '#00FF00', examples: ['🍋', '🌿', '🟢'] },
        { id: 'magenta', name: 'Magenta', color: '#FF00FF', examples: ['🌸', '💜', '🟣'] },
        { id: 'indigo', name: 'Indigo', color: '#4B0082', examples: ['🌌', '💙', '🔵'] },
      ],
      animals: [
        { id: 'lion', name: 'Lion', image: '🦁', sound: 'Roar!' },
        { id: 'tiger', name: 'Tiger', image: '🐯', sound: 'Growl!' },
        { id: 'elephant', name: 'Elephant', image: '🐘', sound: 'Trumpet!' },
        { id: 'giraffe', name: 'Giraffe', image: '🦒', sound: 'Bleat!' },
        { id: 'zebra', name: 'Zebra', image: '🦓', sound: 'Bray!' },
        { id: 'monkey', name: 'Monkey', image: '🐵', sound: 'Ooh ooh!' },
        { id: 'panda', name: 'Panda', image: '🐼', sound: 'Bleat!' },
        { id: 'koala', name: 'Koala', image: '🐨', sound: 'Bellow!' },
        { id: 'dog', name: 'Dog', image: '🐶', sound: 'Woof!' },
        { id: 'cat', name: 'Cat', image: '🐱', sound: 'Meow!' },
        { id: 'cow', name: 'Cow', image: '🐮', sound: 'Moo!' },
        { id: 'pig', name: 'Pig', image: '🐷', sound: 'Oink!' },
        { id: 'sheep', name: 'Sheep', image: '🐑', sound: 'Baa!' },
        { id: 'horse', name: 'Horse', image: '🐴', sound: 'Neigh!' },
        { id: 'duck', name: 'Duck', image: '🦆', sound: 'Quack!' },
        { id: 'chicken', name: 'Chicken', image: '🐔', sound: 'Cluck!' },
        { id: 'rooster', name: 'Rooster', image: '🐓', sound: 'Cock-a-doodle-doo!' },
        { id: 'owl', name: 'Owl', image: '🦉', sound: 'Hoot!' },
        { id: 'bear', name: 'Bear', image: '🐻', sound: 'Growl!' },
        { id: 'rabbit', name: 'Rabbit', image: '🐰', sound: 'Squeak!' },
        { id: 'mouse', name: 'Mouse', image: '🐭', sound: 'Squeak!' },
        { id: 'frog', name: 'Frog', image: '🐸', sound: 'Ribbit!' },
        { id: 'snake', name: 'Snake', image: '🐍', sound: 'Hiss!' },
        { id: 'bird', name: 'Bird', image: '🐦', sound: 'Tweet!' },
        { id: 'fish', name: 'Fish', image: '🐟', sound: 'Blub!' },
        { id: 'whale', name: 'Whale', image: '🐋', sound: 'Sing!' },
        { id: 'dolphin', name: 'Dolphin', image: '🐬', sound: 'Click!' },
        { id: 'shark', name: 'Shark', image: '🦈', sound: 'Chomp!' },
        { id: 'turtle', name: 'Turtle', image: '🐢', sound: 'Gurgle!' },
        { id: 'crab', name: 'Crab', image: '🦀', sound: 'Snap!' },
      ],
      fruits: [
        { id: 'apple', name: 'Apple', image: '🍎', color: 'red' },
        { id: 'banana', name: 'Banana', image: '🍌', color: 'yellow' },
        { id: 'orange', name: 'Orange', image: '🍊', color: 'orange' },
        { id: 'strawberry', name: 'Strawberry', image: '🍓', color: 'red' },
        { id: 'grape', name: 'Grape', image: '🍇', color: 'purple' },
        { id: 'watermelon', name: 'Watermelon', image: '🍉', color: 'green' },
        { id: 'carrot', name: 'Carrot', image: '🥕', color: 'orange' },
        { id: 'tomato', name: 'Tomato', image: '🍅', color: 'red' },
        { id: 'mango', name: 'Mango', image: '🥭', color: 'orange' },
        { id: 'pineapple', name: 'Pineapple', image: '🍍', color: 'yellow' },
        { id: 'cherry', name: 'Cherry', image: '🍒', color: 'red' },
        { id: 'peach', name: 'Peach', image: '🍑', color: 'orange' },
        { id: 'pear', name: 'Pear', image: '🍐', color: 'green' },
        { id: 'kiwi', name: 'Kiwi', image: '🥝', color: 'green' },
        { id: 'lemon', name: 'Lemon', image: '🍋', color: 'yellow' },
        { id: 'coconut', name: 'Coconut', image: '🥥', color: 'brown' },
        { id: 'avocado', name: 'Avocado', image: '🥑', color: 'green' },
        { id: 'broccoli', name: 'Broccoli', image: '🥦', color: 'green' },
        { id: 'corn', name: 'Corn', image: '🌽', color: 'yellow' },
        { id: 'pepper', name: 'Pepper', image: '🫑', color: 'green' },
        { id: 'cucumber', name: 'Cucumber', image: '🥒', color: 'green' },
        { id: 'potato', name: 'Potato', image: '🥔', color: 'brown' },
        { id: 'onion', name: 'Onion', image: '🧅', color: 'white' },
        { id: 'garlic', name: 'Garlic', image: '🧄', color: 'white' },
        { id: 'mushroom', name: 'Mushroom', image: '🍄', color: 'brown' },
        { id: 'peas', name: 'Peas', image: '🫛', color: 'green' },
        { id: 'eggplant', name: 'Eggplant', image: '🍆', color: 'purple' },
        { id: 'cabbage', name: 'Cabbage', image: '🥬', color: 'green' },
        { id: 'lettuce', name: 'Lettuce', image: '🥗', color: 'green' },
        { id: 'radish', name: 'Radish', image: '🍽️', color: 'red' },
      ],
      phonics: [
        { id: 'ph1', sound: 'A', word: 'Ant', image: '🐜' },
        { id: 'ph2', sound: 'B', word: 'Bat', image: '🦇' },
        { id: 'ph3', sound: 'C', word: 'Cat', image: '🐱' },
        { id: 'ph4', sound: 'D', word: 'Dog', image: '🐶' },
        { id: 'ph5', sound: 'E', word: 'Egg', image: '🥚' },
        { id: 'ph6', sound: 'F', word: 'Fish', image: '🐟' },
      ],
    };

    return content[categoryId] || [];
  },
};


